<?php

    $queryString = "";

    if($app!==null){
        if($app==="gestion_cuad"||$app==="directorio"||$app==="reportes"){
            $queryString.="?app=".$app;
        }
    }

?>
<div id="resetbox" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2"> 
    <div class="panel panel-default" >
        <div class="panel-heading">
            <div class="panel-title text-center">Restablecer Contraseña</div>
        </div>
        <div class="row">                
            <div class="iconmelon">
                <img class="img-responsive" src="<?php echo $this->basePath('images/telmex_login.jpg') ?>" alt="TELMEX_IT">
            </div>
        </div>
        <div class="panel-body" >
            <form name="form" id="form-apply-reset" class="form-horizontal" enctype="multipart/form-data" method="POST" action='<?php echo $this->url('reset-pass/apply-reset'); ?>'>
                <?php if ($app !== null) { echo '<input type="hidden" name="app" id="app" value="'.$app.'">'; } ?>
                <input type="hidden" name="token" id="token" value="<?php echo $token; ?>">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input id="newPassword" type="password" class="form-control" name="newPassword" value="" placeholder="Nueva Contraseña">
                </div>
                <div class="errorMessage text-danger"><span id="errornewPassword"></span></div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input id="confirmPassword" type="password" class="form-control" name="confirmPassword" value="" placeholder="Confirmar Contraseña">
                </div>
                <div class="errorMessage text-danger"><span id="errorconfirmPassword"></span></div>
                <div class="form-group">
                    <!-- Button -->
                    <div class="col-sm-12 controls">
                        <button id="submitReset" type="submit" class="btn btn-primary pull-right">Enviar</button>                          
                    </div>
                </div>
            </form>
        </div>                     
    </div>
    <div id="alert" class="alert alert-danger text-justify">
        <p>Reglas para una nueva contraseña:</p>
        <ul class="error text-danger">
            <li>Debe contener entre 8 y 45 carácteres.</li>
            <li>Debe contener letras mayúsculas y minúsculas.</li>
            <li>Debe contener al menos un número.</li>
            <li>Debe contener al menos un carácter especial.</li>
            <li>Carácteres especiales permitidos son <b>.,-_!@#$%^&</b>.</li>
            <li>Evita utilizar una de las últimas 10 contraseñas usadas.</li> 
        </ul>
    </div>
</div>

<div id="ark_loader-apply-reset" class="ark_loader hidden">
    <span>CARGANDO</span>
    <span>
        <div class="sk-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </span>
</div>