<div class="row">
    
    <div class="page-header">
        <h3>Cambio de Contraseña <small><?php echo $auth["userId"]; ?></small></h3>
    </div>
    
    <form id="form-change-password" action="<?php echo $this->url('change-password'); ?>" method="POST">
        
        <div class="clearfix">
            <div class="col-md-6">
                
                <div class="form-group">
                    <div><label for="oldPassword">Contraseña anterior</label></div>
                    <div>
                        <input type="password" class="form-control" name="oldPassword" id="oldPassword" required>
                    </div>
                    <div style="clear:both"><span id="erroroldPassword" class="error text-danger"></span></div>
                </div>
                
                <div class="form-group">
                    <div><label for="newPassword">Contraseña</label></div>
                    <div>
                        <input type="password" class="form-control" name="newPassword" id="newPassword" required>
                    </div>
                    <div style="clear:both"><span id="errornewPassword" class="error text-danger"></span></div>
                </div>
                
                <div class="form-group">
                    <div><label for="confirmPassword">Confirmar Contraseña</label></div>
                    <div>
                        <input type="password" class="form-control" name="confirmPassword" id="confirmPassword" required>
                    </div>
                    <div style="clear:both"><span id="errorconfirmPassword" class="error text-danger"></span></div>
                </div>
            
                <div class="form-group">
                    <div style="clear:both"><span id="errorsubmit" class="error text-danger"></span></div>
                </div>
                
            </div>
            
            <div class="col-md-6">
                <p>Reglas para una nueva contraseña:</p>
                <ul class="error text-danger">
                    <li>Debe contener entre 8 y 45 carácteres.</li>
                    <li>Debe contener letras mayúsculas y minúsculas.</li>
                    <li>Debe contener al menos un número.</li>
                    <li>Debe contener al menos un carácter especial.</li>
                    <li>Carácteres especiales permitidos son <b>.,-_!@#$%^&</b>.</li>
                    <li>Evita utilizar una de las últimas 10 contraseñas usadas.</li> 
                <ul>
            </div>
            
        </div>
        
        <div class="modal-footer">
            <input class="btn btn-primary" type="submit" value="Cambiar" id="submit">
        </div>
        
    </form>
    
    <div id="pass-changed" class="hidden">
        <div class="jumbotron">
            <h3><label></label>, has actualizado satisfactoriamente tu contraseña.</h3>
        </div>
    </div>
    
</div>

<div id="ark_loader-change-pass" class="ark_loader hidden">
    <span>CARGANDO</span>
    <span>
        <div class="sk-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </span>
</div>