<?php

    $queryString = "";

    if($app!==null){
        if($app==="gestion_cuad"||$app==="directorio"||$app==="reportes"){
            $queryString.="?app=".$app;
        }
    }

?>
<div id="loginbox" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2"> 
    <div class="panel panel-default" >
        <div class="panel-heading">
            <div class="panel-title text-center">Iniciar Sesión</div>
        </div>
        <div class="row">                
            <div class="iconmelon">
                <img class="img-responsive" src="<?php echo $this->basePath('images/telmex_login.jpg') ?>" alt="TELMEX_IT">
            </div>
        </div>
        <div class="panel-body" >
            <form name="form" id="login-form" class="form-horizontal" enctype="multipart/form-data" method="POST" action='<?php echo $this->url('login'); ?>'>
                <?php if($app!==null){ echo '<input id="app" type="hidden" name="app" value="'.$app.'">'; }?>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input id="userId" type="text" class="form-control" name="userId" value="" placeholder="Usuario">
                </div>
                <div class="errorMessage text-danger"><span id="erroruserId"></span></div>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                    <input id="password" type="password" class="form-control" name="password" placeholder="Contraseña">
                </div>                                                                  
                <div class="errorMessage text-danger"><span id="errorpassword"></span></div>
                <div class="form-group">
                    <!-- Button -->
                    <div class="col-sm-12 controls">
                        <!--<a href="<?php echo $this->url("reset-pass").$queryString; ?>" id="reset-pass" class="pull-left"><i class="fa fa-reply"></i> Recuperar Contraseña</a>-->
                        <button id="submitLogin" type="submit" class="btn btn-primary pull-right">Entrar</button>                          
                    </div>
                </div>
            </form>
        </div>                     
    </div>
    <?php if($credentials === "expired"){ ?>
    <div id="alert" class="alert alert-danger text-justify">Estimado usuario, la sesión ha expirado por motivos de seguridad. Por favor, vuelva a iniciar sesión. Si usted tiene problemas al ingresar a su cuenta por favor comuniquese a la <b>Mesa de Ayuda</b>.</div>
    <?php } else { ?>
    <div id="alert" class="alert alert-info text-justify">La cuenta de acceso y contraseña es personal e intransferible, el usuario se hace responsable en todo momento de ella.<br />La información contenida en los <b>Aplicativos CUAD</b> tiene carácter confidencial por lo que no deberá ser copiada, divulgada, revelada sin autorización previa.<br />En caso de incumplimiento a cualquiera de las disposiciones anteriormente descritas, <b>TELMEX</b> se reserva el derecho de ejecutar las acciones correspondientes.</div>
    <?php } ?>
</div>

<div id="ark_loader-login" class="ark_loader hidden">
    <span>CARGANDO</span>
    <span>
        <div class="sk-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </span>
</div>