<?php

    $queryString = "";

    if($app!==null){
        if($app==="gestion_cuad"||$app==="directorio"||$app==="reportes"){
            $queryString.="?app=".$app;
        }
    }

?>
<div id="resetbox" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2"> 
    <div class="panel panel-default" >
        <div class="panel-heading">
            <!--<div class="panel-title text-center">Recuperar Contraseña</div>-->
        </div>
        <div class="row">                
            <div class="iconmelon">
                <img class="img-responsive" src="<?php echo $this->basePath('images/telmex_login.jpg') ?>" alt="TELMEX_IT">
            </div>
        </div>
        <div class="panel-body" >
            <form name="form" id="form-reset-password" class="form-horizontal" enctype="multipart/form-data" method="POST" action='<?php echo $this->url('reset-pass'); ?>'>
                <?php if ($app !== null) { echo '<input type="hidden" name="app" id="app" value="'.$app.'">'; } ?>
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                    <input id="userId" type="text" class="form-control" name="userId" value="" placeholder="Usuario">
                </div>
                <div class="errorMessage text-danger"><span id="erroruserId"></span></div>
                <div class="form-group">
                    <!-- Button -->
                    <div class="col-sm-12 controls">
                        <button id="submitReset" type="submit" class="btn btn-primary pull-right">Enviar</button>                          
                    </div>
                </div>
            </form>
        </div>                     
    </div>
    <div id="alert" class="alert alert-info text-justify">La cuenta de acceso y contraseña es personal e intransferible, el usuario se hace responsable en todo momento de ella.<br />La información contenida en los <b>Aplicativos CUAD</b> tiene carácter confidencial por lo que no deberá ser copiada, divulgada, revelada sin autorización previa.<br />En caso de incumplimiento a cualquiera de las disposiciones anteriormente descritas, <b>TELMEX</b> se reserva el derecho de ejecutar las acciones correspondientes.</div>

<div id="ark_loader-reset-pass" class="ark_loader hidden">
    <span>CARGANDO</span>
    <span>
        <div class="sk-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </span>
</div>