<?php

    $queryString = "";

    if($app!==null){
        if($app==="gestion_cuad"||$app==="directorio"||$app==="reportes"){
            $queryString.="?app=".$app;
        }
    }

?>
<div class="row">
    <div class="page-header">
        <h3>Proteger Cuenta <small><?php echo $auth["userId"]; ?></small></h3>
    </div>
    <form id="form-set-email" action="<?php echo $this->url('set-email'); ?>" method="POST">
        <?php if ($app !== null) { echo '<input type="hidden" name="app" id="app" value="'.$app.'">'; } ?>
        <div class="clearfix">
            <div class="col-md-6">
                <div class="form-group">
                    <div><label for="oldPassword">Correo Electrónico</label></div>
                    <div>
                        <input type="email" class="form-control" name="email" id="email" required>
                    </div>
                    <div style="clear:both"><span id="erroremail" class="error text-danger"></span></div>
                </div>
                
                <div class="form-group">
                    <div style="clear:both"><span id="errorsubmit" class="error text-danger"></span></div>
                </div>
                
            </div>
            <div class="col-md-6">
                <p>Al activar su correo electrónico usted esta protegiendo su cuenta para evitar el robo de indentidad por los piratas infórmaticos.</p>
            </div>
        </div>
        <div class="modal-footer">
            <input class="btn btn-primary" type="submit" value="Activar" id="submit">
        </div>
    </form>
</div>

<div id="ark_loader-set-email" class="ark_loader hidden">
    <span>CARGANDO</span>
    <span>
        <div class="sk-fading-circle">
            <div class="sk-circle1 sk-circle"></div>
            <div class="sk-circle2 sk-circle"></div>
            <div class="sk-circle3 sk-circle"></div>
            <div class="sk-circle4 sk-circle"></div>
            <div class="sk-circle5 sk-circle"></div>
            <div class="sk-circle6 sk-circle"></div>
            <div class="sk-circle7 sk-circle"></div>
            <div class="sk-circle8 sk-circle"></div>
            <div class="sk-circle9 sk-circle"></div>
            <div class="sk-circle10 sk-circle"></div>
            <div class="sk-circle11 sk-circle"></div>
            <div class="sk-circle12 sk-circle"></div>
        </div>
    </span>
</div>